hints:
  - For examples of portable application definitions, see https://github.com/ScoopInstaller/Main
  - For examples of non-portable applications, see https://github.com/ScoopInstaller/Nonportable
