# GitHub Pages configuration for scoop-ntwind bucket
theme: jekyll-theme-minimal
title: NTWind Software Scoop Bucket
description: Easy installation of NTWind's Windows utilities through Scoop
show_downloads: false
